// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extract.proto

package gsd.linux;

public final class KconfigProtos {
  private KconfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .Node.NodeType nodeType = 1;
    boolean hasNodeType();
    gsd.linux.KconfigProtos.Node.NodeType getNodeType();
    
    // optional .Node.DataType dataType = 2;
    boolean hasDataType();
    gsd.linux.KconfigProtos.Node.DataType getDataType();
    
    // optional string id = 3;
    boolean hasId();
    String getId();
    
    // optional string description = 4;
    boolean hasDescription();
    String getDescription();
    
    // repeated .PropertyProto property = 5;
    java.util.List<gsd.linux.KconfigProtos.PropertyProto> 
        getPropertyList();
    gsd.linux.KconfigProtos.PropertyProto getProperty(int index);
    int getPropertyCount();
    java.util.List<? extends gsd.linux.KconfigProtos.PropertyProtoOrBuilder> 
        getPropertyOrBuilderList();
    gsd.linux.KconfigProtos.PropertyProtoOrBuilder getPropertyOrBuilder(
        int index);
    
    // optional string inherited = 6;
    boolean hasInherited();
    String getInherited();
    
    // optional bool opt = 10;
    boolean hasOpt();
    boolean getOpt();
    
    // repeated .Node child = 100;
    java.util.List<gsd.linux.KconfigProtos.Node> 
        getChildList();
    gsd.linux.KconfigProtos.Node getChild(int index);
    int getChildCount();
    java.util.List<? extends gsd.linux.KconfigProtos.NodeOrBuilder> 
        getChildOrBuilderList();
    gsd.linux.KconfigProtos.NodeOrBuilder getChildOrBuilder(
        int index);
  }
  public static final class Node extends
      com.google.protobuf.GeneratedMessage
      implements NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(Builder builder) {
      super(builder);
    }
    private Node(boolean noInit) {}
    
    private static final Node defaultInstance;
    public static Node getDefaultInstance() {
      return defaultInstance;
    }
    
    public Node getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gsd.linux.KconfigProtos.internal_static_Node_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gsd.linux.KconfigProtos.internal_static_Node_fieldAccessorTable;
    }
    
    public enum NodeType
        implements com.google.protobuf.ProtocolMessageEnum {
      CONFIG(0, 0),
      MENUCONFIG(1, 1),
      MENU(2, 2),
      CHOICE(3, 3),
      IF(4, 4),
      COMMENT(5, 5),
      UNKNOWN(6, 6),
      ;
      
      public static final int CONFIG_VALUE = 0;
      public static final int MENUCONFIG_VALUE = 1;
      public static final int MENU_VALUE = 2;
      public static final int CHOICE_VALUE = 3;
      public static final int IF_VALUE = 4;
      public static final int COMMENT_VALUE = 5;
      public static final int UNKNOWN_VALUE = 6;
      
      
      public final int getNumber() { return value; }
      
      public static NodeType valueOf(int value) {
        switch (value) {
          case 0: return CONFIG;
          case 1: return MENUCONFIG;
          case 2: return MENU;
          case 3: return CHOICE;
          case 4: return IF;
          case 5: return COMMENT;
          case 6: return UNKNOWN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<NodeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NodeType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NodeType>() {
              public NodeType findValueByNumber(int number) {
                return NodeType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gsd.linux.KconfigProtos.Node.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final NodeType[] VALUES = {
        CONFIG, MENUCONFIG, MENU, CHOICE, IF, COMMENT, UNKNOWN, 
      };
      
      public static NodeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private NodeType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Node.NodeType)
    }
    
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      BOOLEAN(0, 0),
      TRISTATE(1, 1),
      INT(2, 2),
      HEX(3, 3),
      STRING(4, 4),
      ;
      
      public static final int BOOLEAN_VALUE = 0;
      public static final int TRISTATE_VALUE = 1;
      public static final int INT_VALUE = 2;
      public static final int HEX_VALUE = 3;
      public static final int STRING_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static DataType valueOf(int value) {
        switch (value) {
          case 0: return BOOLEAN;
          case 1: return TRISTATE;
          case 2: return INT;
          case 3: return HEX;
          case 4: return STRING;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gsd.linux.KconfigProtos.Node.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final DataType[] VALUES = {
        BOOLEAN, TRISTATE, INT, HEX, STRING, 
      };
      
      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private DataType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Node.DataType)
    }
    
    private int bitField0_;
    // required .Node.NodeType nodeType = 1;
    public static final int NODETYPE_FIELD_NUMBER = 1;
    private gsd.linux.KconfigProtos.Node.NodeType nodeType_;
    public boolean hasNodeType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public gsd.linux.KconfigProtos.Node.NodeType getNodeType() {
      return nodeType_;
    }
    
    // optional .Node.DataType dataType = 2;
    public static final int DATATYPE_FIELD_NUMBER = 2;
    private gsd.linux.KconfigProtos.Node.DataType dataType_;
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public gsd.linux.KconfigProtos.Node.DataType getDataType() {
      return dataType_;
    }
    
    // optional string id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 4;
    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .PropertyProto property = 5;
    public static final int PROPERTY_FIELD_NUMBER = 5;
    private java.util.List<gsd.linux.KconfigProtos.PropertyProto> property_;
    public java.util.List<gsd.linux.KconfigProtos.PropertyProto> getPropertyList() {
      return property_;
    }
    public java.util.List<? extends gsd.linux.KconfigProtos.PropertyProtoOrBuilder> 
        getPropertyOrBuilderList() {
      return property_;
    }
    public int getPropertyCount() {
      return property_.size();
    }
    public gsd.linux.KconfigProtos.PropertyProto getProperty(int index) {
      return property_.get(index);
    }
    public gsd.linux.KconfigProtos.PropertyProtoOrBuilder getPropertyOrBuilder(
        int index) {
      return property_.get(index);
    }
    
    // optional string inherited = 6;
    public static final int INHERITED_FIELD_NUMBER = 6;
    private Object inherited_;
    public boolean hasInherited() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getInherited() {
      Object ref = inherited_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          inherited_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getInheritedBytes() {
      Object ref = inherited_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        inherited_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool opt = 10;
    public static final int OPT_FIELD_NUMBER = 10;
    private boolean opt_;
    public boolean hasOpt() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getOpt() {
      return opt_;
    }
    
    // repeated .Node child = 100;
    public static final int CHILD_FIELD_NUMBER = 100;
    private java.util.List<gsd.linux.KconfigProtos.Node> child_;
    public java.util.List<gsd.linux.KconfigProtos.Node> getChildList() {
      return child_;
    }
    public java.util.List<? extends gsd.linux.KconfigProtos.NodeOrBuilder> 
        getChildOrBuilderList() {
      return child_;
    }
    public int getChildCount() {
      return child_.size();
    }
    public gsd.linux.KconfigProtos.Node getChild(int index) {
      return child_.get(index);
    }
    public gsd.linux.KconfigProtos.NodeOrBuilder getChildOrBuilder(
        int index) {
      return child_.get(index);
    }
    
    private void initFields() {
      nodeType_ = gsd.linux.KconfigProtos.Node.NodeType.CONFIG;
      dataType_ = gsd.linux.KconfigProtos.Node.DataType.BOOLEAN;
      id_ = "";
      description_ = "";
      property_ = java.util.Collections.emptyList();
      inherited_ = "";
      opt_ = false;
      child_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNodeType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropertyCount(); i++) {
        if (!getProperty(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getChildCount(); i++) {
        if (!getChild(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, nodeType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, dataType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDescriptionBytes());
      }
      for (int i = 0; i < property_.size(); i++) {
        output.writeMessage(5, property_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getInheritedBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(10, opt_);
      }
      for (int i = 0; i < child_.size(); i++) {
        output.writeMessage(100, child_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, nodeType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, dataType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDescriptionBytes());
      }
      for (int i = 0; i < property_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, property_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getInheritedBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, opt_);
      }
      for (int i = 0; i < child_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(100, child_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static gsd.linux.KconfigProtos.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsd.linux.KconfigProtos.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsd.linux.KconfigProtos.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsd.linux.KconfigProtos.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsd.linux.KconfigProtos.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsd.linux.KconfigProtos.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static gsd.linux.KconfigProtos.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsd.linux.KconfigProtos.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsd.linux.KconfigProtos.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsd.linux.KconfigProtos.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gsd.linux.KconfigProtos.Node prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gsd.linux.KconfigProtos.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gsd.linux.KconfigProtos.internal_static_Node_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gsd.linux.KconfigProtos.internal_static_Node_fieldAccessorTable;
      }
      
      // Construct using gsd.linux.KconfigProtos.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertyFieldBuilder();
          getChildFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nodeType_ = gsd.linux.KconfigProtos.Node.NodeType.CONFIG;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = gsd.linux.KconfigProtos.Node.DataType.BOOLEAN;
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          propertyBuilder_.clear();
        }
        inherited_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        opt_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (childBuilder_ == null) {
          child_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          childBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gsd.linux.KconfigProtos.Node.getDescriptor();
      }
      
      public gsd.linux.KconfigProtos.Node getDefaultInstanceForType() {
        return gsd.linux.KconfigProtos.Node.getDefaultInstance();
      }
      
      public gsd.linux.KconfigProtos.Node build() {
        gsd.linux.KconfigProtos.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private gsd.linux.KconfigProtos.Node buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        gsd.linux.KconfigProtos.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public gsd.linux.KconfigProtos.Node buildPartial() {
        gsd.linux.KconfigProtos.Node result = new gsd.linux.KconfigProtos.Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeType_ = nodeType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dataType_ = dataType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        if (propertyBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            property_ = java.util.Collections.unmodifiableList(property_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.inherited_ = inherited_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.opt_ = opt_;
        if (childBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            child_ = java.util.Collections.unmodifiableList(child_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.child_ = child_;
        } else {
          result.child_ = childBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gsd.linux.KconfigProtos.Node) {
          return mergeFrom((gsd.linux.KconfigProtos.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(gsd.linux.KconfigProtos.Node other) {
        if (other == gsd.linux.KconfigProtos.Node.getDefaultInstance()) return this;
        if (other.hasNodeType()) {
          setNodeType(other.getNodeType());
        }
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (propertyBuilder_ == null) {
          if (!other.property_.isEmpty()) {
            if (property_.isEmpty()) {
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensurePropertyIsMutable();
              property_.addAll(other.property_);
            }
            onChanged();
          }
        } else {
          if (!other.property_.isEmpty()) {
            if (propertyBuilder_.isEmpty()) {
              propertyBuilder_.dispose();
              propertyBuilder_ = null;
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000010);
              propertyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertyFieldBuilder() : null;
            } else {
              propertyBuilder_.addAllMessages(other.property_);
            }
          }
        }
        if (other.hasInherited()) {
          setInherited(other.getInherited());
        }
        if (other.hasOpt()) {
          setOpt(other.getOpt());
        }
        if (childBuilder_ == null) {
          if (!other.child_.isEmpty()) {
            if (child_.isEmpty()) {
              child_ = other.child_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureChildIsMutable();
              child_.addAll(other.child_);
            }
            onChanged();
          }
        } else {
          if (!other.child_.isEmpty()) {
            if (childBuilder_.isEmpty()) {
              childBuilder_.dispose();
              childBuilder_ = null;
              child_ = other.child_;
              bitField0_ = (bitField0_ & ~0x00000080);
              childBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChildFieldBuilder() : null;
            } else {
              childBuilder_.addAllMessages(other.child_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNodeType()) {
          
          return false;
        }
        for (int i = 0; i < getPropertyCount(); i++) {
          if (!getProperty(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getChildCount(); i++) {
          if (!getChild(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gsd.linux.KconfigProtos.Node.NodeType value = gsd.linux.KconfigProtos.Node.NodeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                nodeType_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              gsd.linux.KconfigProtos.Node.DataType value = gsd.linux.KconfigProtos.Node.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                dataType_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              id_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              description_ = input.readBytes();
              break;
            }
            case 42: {
              gsd.linux.KconfigProtos.PropertyProto.Builder subBuilder = gsd.linux.KconfigProtos.PropertyProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperty(subBuilder.buildPartial());
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              inherited_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000040;
              opt_ = input.readBool();
              break;
            }
            case 802: {
              gsd.linux.KconfigProtos.Node.Builder subBuilder = gsd.linux.KconfigProtos.Node.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addChild(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .Node.NodeType nodeType = 1;
      private gsd.linux.KconfigProtos.Node.NodeType nodeType_ = gsd.linux.KconfigProtos.Node.NodeType.CONFIG;
      public boolean hasNodeType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public gsd.linux.KconfigProtos.Node.NodeType getNodeType() {
        return nodeType_;
      }
      public Builder setNodeType(gsd.linux.KconfigProtos.Node.NodeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        nodeType_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeType_ = gsd.linux.KconfigProtos.Node.NodeType.CONFIG;
        onChanged();
        return this;
      }
      
      // optional .Node.DataType dataType = 2;
      private gsd.linux.KconfigProtos.Node.DataType dataType_ = gsd.linux.KconfigProtos.Node.DataType.BOOLEAN;
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public gsd.linux.KconfigProtos.Node.DataType getDataType() {
        return dataType_;
      }
      public Builder setDataType(gsd.linux.KconfigProtos.Node.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        dataType_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataType_ = gsd.linux.KconfigProtos.Node.DataType.BOOLEAN;
        onChanged();
        return this;
      }
      
      // optional string id = 3;
      private Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
      }
      
      // optional string description = 4;
      private Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
      }
      
      // repeated .PropertyProto property = 5;
      private java.util.List<gsd.linux.KconfigProtos.PropertyProto> property_ =
        java.util.Collections.emptyList();
      private void ensurePropertyIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          property_ = new java.util.ArrayList<gsd.linux.KconfigProtos.PropertyProto>(property_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          gsd.linux.KconfigProtos.PropertyProto, gsd.linux.KconfigProtos.PropertyProto.Builder, gsd.linux.KconfigProtos.PropertyProtoOrBuilder> propertyBuilder_;
      
      public java.util.List<gsd.linux.KconfigProtos.PropertyProto> getPropertyList() {
        if (propertyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(property_);
        } else {
          return propertyBuilder_.getMessageList();
        }
      }
      public int getPropertyCount() {
        if (propertyBuilder_ == null) {
          return property_.size();
        } else {
          return propertyBuilder_.getCount();
        }
      }
      public gsd.linux.KconfigProtos.PropertyProto getProperty(int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);
        } else {
          return propertyBuilder_.getMessage(index);
        }
      }
      public Builder setProperty(
          int index, gsd.linux.KconfigProtos.PropertyProto value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.set(index, value);
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProperty(
          int index, gsd.linux.KconfigProtos.PropertyProto.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProperty(gsd.linux.KconfigProtos.PropertyProto value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProperty(
          int index, gsd.linux.KconfigProtos.PropertyProto value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(index, value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProperty(
          gsd.linux.KconfigProtos.PropertyProto.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProperty(
          int index, gsd.linux.KconfigProtos.PropertyProto.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProperty(
          java.lang.Iterable<? extends gsd.linux.KconfigProtos.PropertyProto> values) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          super.addAll(values, property_);
          onChanged();
        } else {
          propertyBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }
      public Builder removeProperty(int index) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.remove(index);
          onChanged();
        } else {
          propertyBuilder_.remove(index);
        }
        return this;
      }
      public gsd.linux.KconfigProtos.PropertyProto.Builder getPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().getBuilder(index);
      }
      public gsd.linux.KconfigProtos.PropertyProtoOrBuilder getPropertyOrBuilder(
          int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);  } else {
          return propertyBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends gsd.linux.KconfigProtos.PropertyProtoOrBuilder> 
           getPropertyOrBuilderList() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(property_);
        }
      }
      public gsd.linux.KconfigProtos.PropertyProto.Builder addPropertyBuilder() {
        return getPropertyFieldBuilder().addBuilder(
            gsd.linux.KconfigProtos.PropertyProto.getDefaultInstance());
      }
      public gsd.linux.KconfigProtos.PropertyProto.Builder addPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().addBuilder(
            index, gsd.linux.KconfigProtos.PropertyProto.getDefaultInstance());
      }
      public java.util.List<gsd.linux.KconfigProtos.PropertyProto.Builder> 
           getPropertyBuilderList() {
        return getPropertyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gsd.linux.KconfigProtos.PropertyProto, gsd.linux.KconfigProtos.PropertyProto.Builder, gsd.linux.KconfigProtos.PropertyProtoOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gsd.linux.KconfigProtos.PropertyProto, gsd.linux.KconfigProtos.PropertyProto.Builder, gsd.linux.KconfigProtos.PropertyProtoOrBuilder>(
                  property_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }
      
      // optional string inherited = 6;
      private Object inherited_ = "";
      public boolean hasInherited() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getInherited() {
        Object ref = inherited_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          inherited_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setInherited(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        inherited_ = value;
        onChanged();
        return this;
      }
      public Builder clearInherited() {
        bitField0_ = (bitField0_ & ~0x00000020);
        inherited_ = getDefaultInstance().getInherited();
        onChanged();
        return this;
      }
      void setInherited(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        inherited_ = value;
        onChanged();
      }
      
      // optional bool opt = 10;
      private boolean opt_ ;
      public boolean hasOpt() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getOpt() {
        return opt_;
      }
      public Builder setOpt(boolean value) {
        bitField0_ |= 0x00000040;
        opt_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpt() {
        bitField0_ = (bitField0_ & ~0x00000040);
        opt_ = false;
        onChanged();
        return this;
      }
      
      // repeated .Node child = 100;
      private java.util.List<gsd.linux.KconfigProtos.Node> child_ =
        java.util.Collections.emptyList();
      private void ensureChildIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          child_ = new java.util.ArrayList<gsd.linux.KconfigProtos.Node>(child_);
          bitField0_ |= 0x00000080;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          gsd.linux.KconfigProtos.Node, gsd.linux.KconfigProtos.Node.Builder, gsd.linux.KconfigProtos.NodeOrBuilder> childBuilder_;
      
      public java.util.List<gsd.linux.KconfigProtos.Node> getChildList() {
        if (childBuilder_ == null) {
          return java.util.Collections.unmodifiableList(child_);
        } else {
          return childBuilder_.getMessageList();
        }
      }
      public int getChildCount() {
        if (childBuilder_ == null) {
          return child_.size();
        } else {
          return childBuilder_.getCount();
        }
      }
      public gsd.linux.KconfigProtos.Node getChild(int index) {
        if (childBuilder_ == null) {
          return child_.get(index);
        } else {
          return childBuilder_.getMessage(index);
        }
      }
      public Builder setChild(
          int index, gsd.linux.KconfigProtos.Node value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildIsMutable();
          child_.set(index, value);
          onChanged();
        } else {
          childBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setChild(
          int index, gsd.linux.KconfigProtos.Node.Builder builderForValue) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          child_.set(index, builderForValue.build());
          onChanged();
        } else {
          childBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addChild(gsd.linux.KconfigProtos.Node value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildIsMutable();
          child_.add(value);
          onChanged();
        } else {
          childBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addChild(
          int index, gsd.linux.KconfigProtos.Node value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildIsMutable();
          child_.add(index, value);
          onChanged();
        } else {
          childBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addChild(
          gsd.linux.KconfigProtos.Node.Builder builderForValue) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          child_.add(builderForValue.build());
          onChanged();
        } else {
          childBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addChild(
          int index, gsd.linux.KconfigProtos.Node.Builder builderForValue) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          child_.add(index, builderForValue.build());
          onChanged();
        } else {
          childBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllChild(
          java.lang.Iterable<? extends gsd.linux.KconfigProtos.Node> values) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          super.addAll(values, child_);
          onChanged();
        } else {
          childBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearChild() {
        if (childBuilder_ == null) {
          child_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          childBuilder_.clear();
        }
        return this;
      }
      public Builder removeChild(int index) {
        if (childBuilder_ == null) {
          ensureChildIsMutable();
          child_.remove(index);
          onChanged();
        } else {
          childBuilder_.remove(index);
        }
        return this;
      }
      public gsd.linux.KconfigProtos.Node.Builder getChildBuilder(
          int index) {
        return getChildFieldBuilder().getBuilder(index);
      }
      public gsd.linux.KconfigProtos.NodeOrBuilder getChildOrBuilder(
          int index) {
        if (childBuilder_ == null) {
          return child_.get(index);  } else {
          return childBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends gsd.linux.KconfigProtos.NodeOrBuilder> 
           getChildOrBuilderList() {
        if (childBuilder_ != null) {
          return childBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(child_);
        }
      }
      public gsd.linux.KconfigProtos.Node.Builder addChildBuilder() {
        return getChildFieldBuilder().addBuilder(
            gsd.linux.KconfigProtos.Node.getDefaultInstance());
      }
      public gsd.linux.KconfigProtos.Node.Builder addChildBuilder(
          int index) {
        return getChildFieldBuilder().addBuilder(
            index, gsd.linux.KconfigProtos.Node.getDefaultInstance());
      }
      public java.util.List<gsd.linux.KconfigProtos.Node.Builder> 
           getChildBuilderList() {
        return getChildFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gsd.linux.KconfigProtos.Node, gsd.linux.KconfigProtos.Node.Builder, gsd.linux.KconfigProtos.NodeOrBuilder> 
          getChildFieldBuilder() {
        if (childBuilder_ == null) {
          childBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gsd.linux.KconfigProtos.Node, gsd.linux.KconfigProtos.Node.Builder, gsd.linux.KconfigProtos.NodeOrBuilder>(
                  child_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          child_ = null;
        }
        return childBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Node)
    }
    
    static {
      defaultInstance = new Node(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Node)
  }
  
  public interface PropertyProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .PropertyProto.PropertyType propertyType = 1;
    boolean hasPropertyType();
    gsd.linux.KconfigProtos.PropertyProto.PropertyType getPropertyType();
    
    // optional string value = 2;
    boolean hasValue();
    String getValue();
    
    // optional string text = 3;
    boolean hasText();
    String getText();
    
    // optional string visibleExpr = 4;
    boolean hasVisibleExpr();
    String getVisibleExpr();
  }
  public static final class PropertyProto extends
      com.google.protobuf.GeneratedMessage
      implements PropertyProtoOrBuilder {
    // Use PropertyProto.newBuilder() to construct.
    private PropertyProto(Builder builder) {
      super(builder);
    }
    private PropertyProto(boolean noInit) {}
    
    private static final PropertyProto defaultInstance;
    public static PropertyProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gsd.linux.KconfigProtos.internal_static_PropertyProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gsd.linux.KconfigProtos.internal_static_PropertyProto_fieldAccessorTable;
    }
    
    public enum PropertyType
        implements com.google.protobuf.ProtocolMessageEnum {
      PROMPT(0, 0),
      SELECT(1, 1),
      DEFAULT(2, 2),
      DEPENDS_ON(3, 3),
      RANGE(4, 4),
      ENV(5, 5),
      UNKNOWN(6, 6),
      ;
      
      public static final int PROMPT_VALUE = 0;
      public static final int SELECT_VALUE = 1;
      public static final int DEFAULT_VALUE = 2;
      public static final int DEPENDS_ON_VALUE = 3;
      public static final int RANGE_VALUE = 4;
      public static final int ENV_VALUE = 5;
      public static final int UNKNOWN_VALUE = 6;
      
      
      public final int getNumber() { return value; }
      
      public static PropertyType valueOf(int value) {
        switch (value) {
          case 0: return PROMPT;
          case 1: return SELECT;
          case 2: return DEFAULT;
          case 3: return DEPENDS_ON;
          case 4: return RANGE;
          case 5: return ENV;
          case 6: return UNKNOWN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<PropertyType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PropertyType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PropertyType>() {
              public PropertyType findValueByNumber(int number) {
                return PropertyType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gsd.linux.KconfigProtos.PropertyProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final PropertyType[] VALUES = {
        PROMPT, SELECT, DEFAULT, DEPENDS_ON, RANGE, ENV, UNKNOWN, 
      };
      
      public static PropertyType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private PropertyType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:PropertyProto.PropertyType)
    }
    
    private int bitField0_;
    // required .PropertyProto.PropertyType propertyType = 1;
    public static final int PROPERTYTYPE_FIELD_NUMBER = 1;
    private gsd.linux.KconfigProtos.PropertyProto.PropertyType propertyType_;
    public boolean hasPropertyType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public gsd.linux.KconfigProtos.PropertyProto.PropertyType getPropertyType() {
      return propertyType_;
    }
    
    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getText() {
      Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string visibleExpr = 4;
    public static final int VISIBLEEXPR_FIELD_NUMBER = 4;
    private Object visibleExpr_;
    public boolean hasVisibleExpr() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getVisibleExpr() {
      Object ref = visibleExpr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          visibleExpr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVisibleExprBytes() {
      Object ref = visibleExpr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        visibleExpr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      propertyType_ = gsd.linux.KconfigProtos.PropertyProto.PropertyType.PROMPT;
      value_ = "";
      text_ = "";
      visibleExpr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPropertyType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, propertyType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getVisibleExprBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, propertyType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getVisibleExprBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static gsd.linux.KconfigProtos.PropertyProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsd.linux.KconfigProtos.PropertyProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gsd.linux.KconfigProtos.PropertyProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gsd.linux.KconfigProtos.PropertyProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gsd.linux.KconfigProtos.internal_static_PropertyProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gsd.linux.KconfigProtos.internal_static_PropertyProto_fieldAccessorTable;
      }
      
      // Construct using gsd.linux.KconfigProtos.PropertyProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        propertyType_ = gsd.linux.KconfigProtos.PropertyProto.PropertyType.PROMPT;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        visibleExpr_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gsd.linux.KconfigProtos.PropertyProto.getDescriptor();
      }
      
      public gsd.linux.KconfigProtos.PropertyProto getDefaultInstanceForType() {
        return gsd.linux.KconfigProtos.PropertyProto.getDefaultInstance();
      }
      
      public gsd.linux.KconfigProtos.PropertyProto build() {
        gsd.linux.KconfigProtos.PropertyProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private gsd.linux.KconfigProtos.PropertyProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        gsd.linux.KconfigProtos.PropertyProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public gsd.linux.KconfigProtos.PropertyProto buildPartial() {
        gsd.linux.KconfigProtos.PropertyProto result = new gsd.linux.KconfigProtos.PropertyProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.propertyType_ = propertyType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.visibleExpr_ = visibleExpr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gsd.linux.KconfigProtos.PropertyProto) {
          return mergeFrom((gsd.linux.KconfigProtos.PropertyProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(gsd.linux.KconfigProtos.PropertyProto other) {
        if (other == gsd.linux.KconfigProtos.PropertyProto.getDefaultInstance()) return this;
        if (other.hasPropertyType()) {
          setPropertyType(other.getPropertyType());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasVisibleExpr()) {
          setVisibleExpr(other.getVisibleExpr());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPropertyType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gsd.linux.KconfigProtos.PropertyProto.PropertyType value = gsd.linux.KconfigProtos.PropertyProto.PropertyType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                propertyType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              text_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              visibleExpr_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .PropertyProto.PropertyType propertyType = 1;
      private gsd.linux.KconfigProtos.PropertyProto.PropertyType propertyType_ = gsd.linux.KconfigProtos.PropertyProto.PropertyType.PROMPT;
      public boolean hasPropertyType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public gsd.linux.KconfigProtos.PropertyProto.PropertyType getPropertyType() {
        return propertyType_;
      }
      public Builder setPropertyType(gsd.linux.KconfigProtos.PropertyProto.PropertyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        propertyType_ = value;
        onChanged();
        return this;
      }
      public Builder clearPropertyType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        propertyType_ = gsd.linux.KconfigProtos.PropertyProto.PropertyType.PROMPT;
        onChanged();
        return this;
      }
      
      // optional string value = 2;
      private Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // optional string text = 3;
      private Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getText() {
        Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
      }
      
      // optional string visibleExpr = 4;
      private Object visibleExpr_ = "";
      public boolean hasVisibleExpr() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getVisibleExpr() {
        Object ref = visibleExpr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          visibleExpr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVisibleExpr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        visibleExpr_ = value;
        onChanged();
        return this;
      }
      public Builder clearVisibleExpr() {
        bitField0_ = (bitField0_ & ~0x00000008);
        visibleExpr_ = getDefaultInstance().getVisibleExpr();
        onChanged();
        return this;
      }
      void setVisibleExpr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        visibleExpr_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PropertyProto)
    }
    
    static {
      defaultInstance = new PropertyProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PropertyProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PropertyProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PropertyProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rextract.proto\"\350\002\n\004Node\022 \n\010nodeType\030\001 \002" +
      "(\0162\016.Node.NodeType\022 \n\010dataType\030\002 \001(\0162\016.N" +
      "ode.DataType\022\n\n\002id\030\003 \001(\t\022\023\n\013description\030" +
      "\004 \001(\t\022 \n\010property\030\005 \003(\0132\016.PropertyProto\022" +
      "\021\n\tinherited\030\006 \001(\t\022\013\n\003opt\030\n \001(\010\022\024\n\005child" +
      "\030d \003(\0132\005.Node\"^\n\010NodeType\022\n\n\006CONFIG\020\000\022\016\n" +
      "\nMENUCONFIG\020\001\022\010\n\004MENU\020\002\022\n\n\006CHOICE\020\003\022\006\n\002I" +
      "F\020\004\022\013\n\007COMMENT\020\005\022\013\n\007UNKNOWN\020\006\"C\n\010DataTyp" +
      "e\022\013\n\007BOOLEAN\020\000\022\014\n\010TRISTATE\020\001\022\007\n\003INT\020\002\022\007\n" +
      "\003HEX\020\003\022\n\n\006STRING\020\004\"\332\001\n\rPropertyProto\0221\n\014",
      "propertyType\030\001 \002(\0162\033.PropertyProto.Prope" +
      "rtyType\022\r\n\005value\030\002 \001(\t\022\014\n\004text\030\003 \001(\t\022\023\n\013" +
      "visibleExpr\030\004 \001(\t\"d\n\014PropertyType\022\n\n\006PRO" +
      "MPT\020\000\022\n\n\006SELECT\020\001\022\013\n\007DEFAULT\020\002\022\016\n\nDEPEND" +
      "S_ON\020\003\022\t\n\005RANGE\020\004\022\007\n\003ENV\020\005\022\013\n\007UNKNOWN\020\006B" +
      "\032\n\tgsd.linuxB\rKconfigProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Node_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Node_descriptor,
              new java.lang.String[] { "NodeType", "DataType", "Id", "Description", "Property", "Inherited", "Opt", "Child", },
              gsd.linux.KconfigProtos.Node.class,
              gsd.linux.KconfigProtos.Node.Builder.class);
          internal_static_PropertyProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PropertyProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PropertyProto_descriptor,
              new java.lang.String[] { "PropertyType", "Value", "Text", "VisibleExpr", },
              gsd.linux.KconfigProtos.PropertyProto.class,
              gsd.linux.KconfigProtos.PropertyProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
